
#+TITLE: SIR-recovery
#+AUTHOR: Ramakrishna Suresh
#+PROPERTY: header-args:julia-vterm :session *julia* :results output :exports both :dir (projectile-project-root) :comment both :tangle yes
#+STARTUP: inlineimages overview

* Boilerplate

#+begin_src julia-vterm
using Pkg;
Pkg.activate(".")
#+end_src

#+RESULTS:

#+begin_src julia-vterm
using ComponentArrays
using Lux, NNlib
using Optimization, OptimizationOptimisers, OptimizationOptimJL
using Enzyme
using ForwardDiff
using Statistics
using Random
using Base.Threads
using DifferentialEquations
using CairoMakie, Makie
using CSV, DataFrames
using Pkg
using Random, Statistics

include(
    joinpath(pwd(), "Src", "Fitting.jl")
)

#+end_src

#+RESULTS:

 
* Creating and saving the toy dataset

We create a struct named ~SIRParams~ containing the rate constants \beta and \gamma to be
used in our model. The current workflow assumes the usage of structs to avoid
mistakes with indexed parameters and possible typos.
#+begin_src julia-vterm
struct SIRParams{T<:AbstractFloat}
    β::T   # infection rate in normalized I-equation
    γ::T   # recovery rate  in normalized I-equation
end
#+end_src

#+RESULTS:
: Executing... dc68c4b8

To create the toy dataset, we use the following model equations for and SIR
model:

#+NAME: eq:prelim-SIR-true
\begin{subequations}
\begin{align}
&\frac{dS}{dt} = -\beta \cdot S \cdot I \\
&\frac{dI}{dt} = \beta \cdot S \cdot I - \gamma \cdot I\\
&\frac{dR}{dt} = \gamma \cdot I
\end{align}
\end{subequations}

The default parameters are as follows:

#+NAME: table:SIR-true-params
#+ATTR_LATEX: :align ccc
#+CAPTION: True parameters used by SIR model equations [[eq:prelim-SIR-true]] to generate mock data.
|-----------+-------------------+-------|
| Parameter | Parameter Name    | Value |
|-----------+-------------------+-------|
| \beta         | Transmission Rate |   1.5 |
| \gamma         | Recovery Rate     |     1 |
|-----------+-------------------+-------|
We use ~DifferentialEquations.jl~ package syntax to solve the known ODE system
over the timespan ~t_span~ \in [0, 6]. Random multiplicative noise is assumed and is
added to the solution to create the noisy dataset. The following code block can
be uncommented to generate the dataset. To maintain consistency with the
published results, the CSV file named ~SIR_train.csv~, generated by running the
following code block, will be used for all analyses hereon.

#+begin_src julia-vterm

# # SIR model method for DifferentialEquations call 
# function SIR_model!(du, u, p::SIRParams, t)
#     S, I, R = u
#     du[1] = -p.β * S * I 
#     du[2] =  p.β * S * I - p.γ * I
#     du[3] =  p.γ * I
# end

# # Fast default RNG. Does not get messed up with a global RNG
# rng = Random.MersenneTwister(42)

# # Start with our true known parameters
# true_SIR_par = SIRParams(1.5f0, 1f0)
# t_span = (0.0f0, 6.0f0)
# N_obs = 101

# # Collect seems to turn an iterable into an array
# t_obs_array = range(t_span[1], t_span[2], length=N_obs) |> collect
# u0 = [3, 0.001, 0.0]

# # solve the ODE to get a solution object
# prob = DifferentialEquations.ODEProblem(SIR_model!, u0, t_span, true_SIR_par)
# sol = DifferentialEquations.solve(
#     prob,
#     DifferentialEquations.Tsit5();
#     saveat = t_obs_array
# )
# # Convert the solution object into an Array
# sol_ = Array(sol)

# # multiplicative % noise via lognormal, unbiased & positive 
# noise_pct = 0.2
# ε = Random.randn(rng, size(sol_)...)
# noisy_data = sol_ .* exp.(noise_pct .* ε .- 0.5 * noise_pct^2) 
# noisy_data = clamp.(noisy_data, 0, Inf32)

# # Convert to Float32 to keep everyone happy
# t_train = Float32.(t_obs_array)
# Y_train = Float32.(noisy_data)
# y0_obs  = sol_[:, 1]     # IC for penalty

# Y_train_std = Statistics.std(Y_train, dims=2);
# Y_max = maximum(Y_train; dims=2)

# # Split true (ODE) solution
# S_true = sol_[1, :]
# I_true = sol_[2, :]
# R_true = sol_[3, :]

# # Split noisy measurements
# S_noisy = Y_train[1, :]
# I_noisy = Y_train[2, :]
# R_noisy = Y_train[3, :]

# # Construct a DataFrame for saving
# df = DataFrame(
#     t       = t_train,
#     S_true  = Float32.(S_true),
#     I_true  = Float32.(I_true),
#     R_true  = Float32.(R_true),
#     S = S_noisy,
#     I = I_noisy,
#     R = R_noisy,
# )

# CSV.write(
#     joinpath(pwd(), "Results", "SIR_train.csv"),
#     df
# )
#+end_src

#+RESULTS:

* Creating the training vector and visualizing the dataset

The following code chunk reads the ~SIR_train.csv~ and prepares the vectors
~t_train~ and ~Y_train~ to be used to perform the training. ~Y_train_actual~ is a
vector containing the noisy SIR dataset, which then gets normalized by the
maximum of each state such that the resulting ~Y_train~ \in [0,1]. This is done
specifically to aid the optimizer to correctly fit the model to data for all the
states, as the likelihood space tends to be sensitive mainly to the state with
the largest scale otherwise. 

#+begin_src julia-vterm

df = CSV.read(
    joinpath(pwd(), "Results", "SIR_train.csv"),
    DataFrame
)

true_sol = permutedims(
    Matrix{Float32}(
        df[
            :,
            [:S_true, :I_true, :R_true ]
        ]
    )
)

# Split true (ODE) solution
S_true = true_sol[1, :]
I_true = true_sol[2, :]
R_true = true_sol[3, :]


Y_train_actual = permutedims(
    Matrix{Float32}(
        df[
            :,
            [:S, :I, :R ]
        ]
    )
)

t_train = permutedims(
    Matrix{Float32}(
        df[
            :,
            [:t]
        ]
    )
)

# Normalize the dataset
Y_max = maximum(Y_train_actual; dims=2)
Y_train = Y_train_actual./Y_max

#+end_src

#+RESULTS:

The following code chunk visualizes the noisy training dataset ~Y_train~ along
with the noise-free, true solution from the ODE solver. Uncomment either the
~display(fig)~ line or the ~save(...)~ lines as per needs.

#+begin_src julia-vterm

# CairoMakie.activate!(type = "svg")

fig = Figure(size = (800, 600), fontsize = 14)

# Common axis styling
axis_kwargs = (
    xlabel = "Time",
    ylabel = "Population",
    xgridvisible = true,
    ygridvisible = true,
    topspinevisible = false,
    rightspinevisible = false,
    xticklabelsize = 10,
    yticklabelsize = 10,
    titlesize = 14,
    titlealign = :left,
)

# Arrange as 3 stacked panels with shared x
axS = CairoMakie.Axis(fig[1, 1]; title = "Susceptible S(t)", axis_kwargs...)
axI = CairoMakie.Axis(fig[2, 1]; title = "Infectious I(t)", axis_kwargs...)
axR = CairoMakie.Axis(fig[3, 1]; title = "Recovered R(t)", axis_kwargs...)

Makie.linkxaxes!(axS, axI, axR)

# --- Plot model vs data ---
# Use consistent, print-friendly styling
line_kwargs = (color = :black, linewidth = 2)
scatter_kwargs = (marker = :circle, markersize = 7,
                  color = :white, strokecolor = :black, strokewidth = 1.5)

lS = lines!(axS, t_train[1, :], S_true; label = "True Model", line_kwargs...)
sS = scatter!(axS, t_train[1, :], Y_train_actual[1, :]; label = "Data", scatter_kwargs...)

lI = lines!(axI, t_train[1, :], I_true; label = "True Model", line_kwargs...)
sI = scatter!(axI, t_train[1, :], Y_train_actual[2, :]; label = "Data", scatter_kwargs...)

lR = lines!(axR, t_train[1, :], R_true; label = "True Model", line_kwargs...)
sR = scatter!(axR, t_train[1, :], Y_train_actual[3, :]; label = "Data", scatter_kwargs...)

# --- Single shared legend at the top or bottom ---
Legend(fig[0, 1], [lS, sS], ["True ODE Model", "Data"], orientation = :horizontal, tellwidth = false)

# alternatively at bottom:
# Legend(fig[4, 1], [lS, sS], ["NN(t, θ_g)", "Data"], orientation = :horizontal)


display(fig)


# save(
#     joinpath(pwd(), "Results", "SIR_Data_Viz.pdf"),
#     fig,
#     px_per_unit = 600/72  # Convert to DPI
#     )

#+end_src

#+RESULTS:


* Building the architecture

Architecture here refers to the "grey-box" mathematical formulation of the sum
of known and unknown physics. To create such an architecture, we have to start
with deciding what is known and unknown about our toy system. In this case, we
assume the generation term for Susceptible (S) and Recovered (R) states are
unknown. This is currently an arbitrary assumption. The resulting architecture
has the following governing equations:

#+NAME: eq:prelim-SIR-formulation
\begin{subequations}
\begin{align}
&\frac{dS}{dt} = \mathrm{g}_S(t, \theta_g) \\
&\frac{dI}{dt} = \beta \cdot S \cdot I - \gamma \cdot I\\
&\frac{dR}{dt} = \mathrm{g}_R(t, \theta_g)
\end{align}
\end{subequations}


We create a function ~SIRarchitecturenorm~ which takes in ~y~ and ~g~, of an
~AbstractMatrix{<:Real}~ datatype, along with ~p~, which should be an ~SIRParams~
struct object. This function takes y and g to calculate the $\frac{dy}{dt}$ matrix.

#+begin_src julia-vterm

# Physics parameters in normalized coordinates (I-equation):
#   dĨ/dt = β * Ŝ - γ * Ĩ
struct SIRParams{T<:AbstractFloat}
    β::T   # infection rate in normalized I-equation
    γ::T   # recovery rate  in normalized I-equation
end

SIRParams(nt::ComponentVector) = SIRParams(
    nt.β, nt.γ
)

function SIRArchitectureNorm(
    ỹ::AbstractMatrix{<:Real},   # 3×B (S̃, Ĩ, R̃)
    g̃::AbstractMatrix{<:Real},   # 2×B (g_S, g_R)
    p::SIRParams,
)
    @assert size(ỹ, 1) == 3 "ỹ must have 3 states (Ŝ, Ĩ, R̃)"
    @assert size(g̃, 1) == 2 "g̃ must have 2 outputs (g_S, g_R)"

    S̃ = ỹ[1, :]   
    Ĩ = ỹ[2, :]
    # R̃ = ỹ[3, :]   
    g_S = g̃[1, :]
    g_R = g̃[2, :]
    

    # Unknown physics in S and R equations:
    dS̃ = g_S

    dĨ = p.β .* S̃ .* Ĩ .- p.γ .* Ĩ

    dR̃ = g_R

    # Return as 3×B to match the rest of your pipeline
    return permutedims(hcat(dS̃, dĨ, dR̃))
end

#+end_src

#+RESULTS:

* Initializing the MLPs

Since the $\mathrm{g}$ and $\mathrm{u}$ are unknown physics, we use MLPs to fit
the residuals. The MLPs are initialized as follows:

#+begin_src julia-vterm

build_state_mlp() = Lux.Chain(
    Lux.Dense(1, 6, tanh_fast),
    Lux.Dense(6, 4, tanh_fast),
    Lux.Dense(4, 3, NNlib.sigmoid_fast) # forces outputs to be positive
)
# NN for the unknown physics g_S, g_R in normalized units
build_g_mlp() = Lux.Chain(
    Lux.Dense(1, 5, tanh_fast),
    Lux.Dense(5, 4, tanh_fast),
    Lux.Dense(4, 2) # This output can be negative
)
#+end_src

#+RESULTS:

The size of the MLPs are currently arbitratry, with the only condition being the
total number of parameters needing to be less than the number of training
datapoints.

* Aggregating everything into a named tuple

The optimzer needs an abstraction of model, data and parameters. In our case, we
have optimized parameters (the MLP params for eg) and non-optimized parameters
(the optimizer guesses, the tspan, etc.) being fed to the optimizer. We can
aggregate the non-optimized parameters along with data into a ~tuple~.

#+begin_src julia-vterm

# IC in normalized units
y0_init = Float32.([3, 0.001, 0.0])./Y_max

# Dense time grid and span
t_dense = permutedims(Float32.(range(
    minimum(t_train), maximum(t_train), length=1000
)))
t_span = Float32[minimum(t_train), maximum(t_train)]

# Initial guesses for normalized parameters β_norm, γ
guess_SIRparams = SIRParams(1.0f0, 1.0f0)  # choose something reasonable

# Bounds for β, γ (in normalized units)
β_bounds = Float32[0f0, 10f0]
γ_bounds = Float32[0f0, 10f0]

data = (
    t_train       = t_train,
    Y_train       = Y_train,
    Y_train_std   = permutedims([1,1,1]'),
    t_dense       = t_dense,
    t_span        = t_span,
    y0_init       = y0_init,
    ODE_par_init  = (
        β = guess_SIRparams.β,
        γ = guess_SIRparams.γ,
    ),
    ODE_par_bounds = (
        β = β_bounds,
        γ = γ_bounds,
    ),
)
#+end_src

#+RESULTS:

* Optional callback function for visually inspecting the optimization running

This callback function aims to plot the data and the optimizer state at user
specified iteration count given by the ~plot_every~ argument.

#+begin_src julia-vterm

# history of (time, prediction) for plotting in the callback
trajectory_history = NamedTuple[]  # Vector{NamedTuple} with (t = ::Vector, y = ::Matrix)

# using CairoMakie

global cb_fig = CairoMakie.Figure(size = (900, 600))
global cb_ax1 = CairoMakie.Axis(cb_fig[1, 1]; title = "V")
global cb_ax2 = CairoMakie.Axis(cb_fig[1, 2]; title = "IFN")
global cb_ax3 = CairoMakie.Axis(cb_fig[2, 1]; title = "M")

# display(cb_fig)   # show it once

function callback_fixed(state, l, Architecture::Function, ODE_params; plot_every = 20_000)
    # --- logging as before ---
    N = 25
    if state.iter % N == 0
        if state.iter % (N * 1000) == 0
            println("iteration =", state.iter)
        end
        ps  = state.u
        ctx = state.p

        d_mse = loss_Data(ps, ctx)
        if ctx isa PINNCtxStage2
            o_mse = loss_ODE(ps, ctx, Architecture, ODE_params)
            gmodel = g_model(ps, ctx)
            Tdense = ctx.t_dense
            g_out  = gmodel(Tdense)
            g_s    = std(vec(g_out))
        else
            o_mse = 50
            g_s   = 50
        end

        push!(iter_hist, state.iter)
        push!(data_mse_hist, d_mse)
        push!(ode_mse_hist, o_mse)
        push!(g_std_hist, g_s)
    end

    # -- update plot every 25_000 iters --
    plot_every = 10_000
    if state.iter % plot_every == 0
        ps  = state.u
        ctx = state.p
        smodel = state_model(ps, ctx)

        # data times (for scatter) – always from training data
        t_data = vec(ctx.t_train)
        Y      = ctx.Y_train

        # prediction times (for trajectories)
        if ctx isa PINNCtxStage1
            # dense grid over data time range
            t_plot_vec = Float32.(
                collect(range(first(t_data), last(t_data), length=200))
            )
            t_plot     = permutedims(t_plot_vec)      # 1×200 for smodel
            y_pred     = smodel(t_plot)              # 3×200
        else
            t_plot     = ctx.t_dense                 # 1×Nd
            t_plot_vec = vec(t_plot)                 # Nd
            y_pred     = smodel(t_plot)             # 3×Nd
        end

        # store trajectory
        global trajectory_history
        push!(trajectory_history, (t = t_plot_vec, y = y_pred))
        if length(trajectory_history) > 10
            popfirst!(trajectory_history)
        end

        # clear the axes
        Makie.empty!(cb_ax1)
        Makie.empty!(cb_ax2)
        Makie.empty!(cb_ax3)

        # redraw data scatter (t_data, not t_plot_vec)
        scatter!(cb_ax1, t_data, Y[1, :]; label = "Data S")
        scatter!(cb_ax2, t_data, Y[2, :]; label = "Data I")
        scatter!(cb_ax3, t_data, Y[3, :]; label = "Data R")

        # redraw all stored trajectories w/ transparency
        ntraj = length(trajectory_history)
        for (k, tr) in enumerate(trajectory_history)
            α = 0.15 + 0.65 * (k / ntraj)
            col = (:blue, α)
            label = k == ntraj ? "NN(t,θ)" : nothing

            lines!(cb_ax1, tr.t, tr.y[1, :]; color = col, label = label)
            lines!(cb_ax2, tr.t, tr.y[2, :]; color = col)
            lines!(cb_ax3, tr.t, tr.y[3, :]; color = col)
        end

        axislegend(cb_ax1)
        axislegend(cb_ax2)
        axislegend(cb_ax3)

        display(cb_fig)
    end

    return false
end



callback_fixed_closure = (state, l) -> callback_fixed(state, l, SIRArchitectureNorm, SIRParams)
# callback_closure = (state, l) -> callback(state, l, LiparuloArchitecture, LiparuloKnownParams)

#+end_src

#+RESULTS:

* Adding penalties as more prior information

We assume the prior knowledge of positive production rates only at starting time
points just to make sure the optimizer doesn't delve into weird solution
spaces. This is not currently needed for satisfactorily running the SIR test
model. 

#+begin_src julia-vterm

function nonneg_production_penalty(ps, ctx::PINNCtxStage2; scale=1000f0)
    # This is somewhat Liparulo-specific (assumes g has 3 outputs, penalize 2..3)
    gmodel = g_model(ps, ctx)
    ystart = gmodel(ctx.t_dense[:, 1:50])         # 3×50; Arbitrary first 50 time array indices
    sum(NNlib.relu.(-ystart[2:3, :]).^2).* scale
end

#+end_src

#+RESULTS:

* Running the optimization algorithm

#+begin_src julia-vterm
hp = HyperParams(
    1.0/2.0f0,
    1.0/10.0f0,
    1/25.0f0,
    1/√(750f-3),
)
data_mse_hist = Float32[]
ode_mse_hist  = Float32[]
g_std_hist    = Float32[]
iter_hist     = Int[]
iter_counter  = Ref(0)


stats = @timed res = train_fixed_hyper(
    data,
    SIRArchitectureNorm,
    SIRParams,
    hp;
    user_loss_functions = Function[],
    maxiters_stage1     = 50_000,
    maxiters_stage2     = 120_000,
    Opt_alg_stage1      = OptimizationOptimisers.Adam(1f-4),
    Opt_alg_stage2      = OptimizationOptimisers.Adam(1f-4),
#    callback_function = callback_fixed_closure
)

println("Training time: $(stats.time) seconds")
println("Memory used:   $(stats.bytes / 1e6) MB")
#+end_src

#+RESULTS:


* Visualizing the final fit results

The final fit $\mathrm{u}$'s predictions are overlayed on the training dataset.

#+begin_src julia-vterm

using CairoMakie, Makie
# --- Evaluate the model as before ---
smodel = state_model(res.params, res.ctx2)

t_plot = Float32.(collect(range(first(t_span), last(t_span), length = 200)))
t_plot = permutedims(t_plot)            # (1, N)
tvec   = vec(t_plot)                    # (N,)

sŷ = smodel(t_plot)                    # size ≈ (3, length(tvec))

# --- Figure + theme ---
fig = Figure(size = (800, 600), fontsize = 14)

# Common axis styling
axis_kwargs = (
    xlabel = "Time t",
    ylabel = "Population",
    xgridvisible = true,
    ygridvisible = true,
    topspinevisible = false,
    rightspinevisible = false,
    xticklabelsize = 10,
    yticklabelsize = 10,
    titlesize = 14,
    titlealign = :left,
)

# Arrange as 3 stacked panels with shared x
axS = CairoMakie.Axis(fig[1, 1]; title = "Susceptible S(t)", axis_kwargs...)
axI = CairoMakie.Axis(fig[2, 1]; title = "Infectious I(t)", axis_kwargs...)
axR = CairoMakie.Axis(fig[3, 1]; title = "Recovered R(t)", axis_kwargs...)

Makie.linkxaxes!(axS, axI, axR)

# --- Plot model vs data ---
# Use consistent, print-friendly styling
line_kwargs = (color = :black, linewidth = 2)
scatter_kwargs = (marker = :circle, markersize = 7,
                  color = :white, strokecolor = :black, strokewidth = 1.5)


ldS = lines!(axS, t_train[1, :], S_true./Y_max[1]; label = "True Model", line_kwargs...)
ldI = lines!(axI, t_train[1, :], I_true./Y_max[2]; label = "True Model", line_kwargs...)

ldR = lines!(axR, t_train[1, :], R_true./Y_max[3]; label = "True Model", line_kwargs...)

lS = lines!(axS, tvec, sŷ[1, :]; label = "NN(t, θ_u)", line_kwargs...)
sS = scatter!(axS, vec(t_train), Y_train[1, :]; label = "Data", scatter_kwargs...)

lI = lines!(axI, tvec, sŷ[2, :]; label = "NN(t, θ_u)", line_kwargs...)
sI = scatter!(axI, vec(t_train), Y_train[2, :]; label = "Data", scatter_kwargs...)

lR = lines!(axR, tvec, sŷ[3, :]; label = "NN(t, θ_u)", line_kwargs...)
sR = scatter!(axR, vec(t_train), Y_train[3, :]; label = "Data", scatter_kwargs...)

# --- Single shared legend at the top or bottom ---
Legend(fig[0, 1], [ldS,lS, sS], ["True Model", "NN(t, θ_g)", "Data"], orientation = :horizontal, tellwidth = false)
# alternatively at bottom:
# Legend(fig[4, 1], [lS, sS], ["NN(t, θ_g)", "Data"], orientation = :horizontal)

display(fig)

# save(
#     joinpath(pwd(), "Results", "SIR_NN_fit.pdf"),
#     fig,
#     px_per_unit = 600/72
#     )
# save("sir_fit.pdf", fig, pt_per_unit = 1.0)
# save("sir_fit.png", fig, px_per_unit = 3.0)

#+end_src

#+RESULTS:
: Executing... ddfe93e8

The fit $\mathrm{g}$ for each state is overlayed on ground truth.

#+begin_src julia-vterm
using CairoMakie
using Makie  

g1 = -1.5 .* S_true .* I_true ./ Y_max[1]
g2 = 1 .* I_true ./ Y_max[3]

g_true = permutedims(hcat(g1,g2))
# --- Evaluate explicit g-model ---
gmodel = g_model(res.params, res.ctx2)

t_plot = Float32.(collect(range(first(t_span), last(t_span), length = 200)))
t_plot = permutedims(t_plot)             # 1×N
tvec   = vec(t_plot)

gŷ = gmodel(t_plot)                     # should return 2×N or 3×N


# --- Figure setup ---
fig = CairoMakie.Figure(size = (900, 350), fontsize = 14)

axis_kwargs = (
    xlabel = "Time",
    ylabel = "Rate",
    xgridvisible = true,
    ygridvisible = true,
    topspinevisible = false,
    rightspinevisible = false,
    xticklabelsize = 10,
    yticklabelsize = 10,
    titlesize = 14,
    titlealign = :left,
)

axS = CairoMakie.Axis(fig[1, 1]; title = "g_S(t, θ_g)", axis_kwargs...)
axR = CairoMakie.Axis(fig[1, 2]; title = "g_R(t, θ_g)", axis_kwargs...)

# Link x-axes if supported by your Makie version

Makie.linkxaxes!(axS, axR)



# --- Plot styling ---
trained_kwargs = (color = :black, linewidth = 2)
nn_kwargs      = (color = :gray, linestyle = :dash, linewidth = 2)

# g_S
lS_trained = CairoMakie.lines!(axS, tvec, gŷ[1, :]; label = "g trained", trained_kwargs...)
lS_nn      = CairoMakie.lines!(axS, vec(t_train),  g_true[1, :]; label = "g from NN", nn_kwargs...)

# g_R
lR_trained = CairoMakie.lines!(axR, tvec, gŷ[2, :]; label = "g trained", trained_kwargs...)
lR_nn      = CairoMakie.lines!(axR, vec(t_train),  g_true[2, :]; label = "g from NN", nn_kwargs...)

# --- Shared legend ---
CairoMakie.Legend(fig[2, 1:2], [lS_trained, lS_nn],
                  ["g trained", "g true"],
                  orientation = :horizontal, tellwidth = false)

# CairoMakie.save(
#     joinpath(project_root_dir, "Results", "SIR_g_visualization.pdf"),
#     fig; px_per_unit = 300/72)
display(fig)


# --- 300 dpi export ---
# DPI = px_per_unit * 72 → px_per_unit = 300 / 72
#+end_src

#+RESULTS:

* Using symbolic regression

#+begin_src julia-vterm

using SymbolicRegression

# 1. Get state and g models on the dense training grid
ps  = res.params
ctx = res.ctx2

smodel = state_model(ps, ctx)
gmodel = g_model(ps, ctx)

t_dense = ctx.t_dense              # 1×B, same grid used in training
t_vec   = vec(t_dense)             # B

# Forward passes (normalized coordinates)
Ỹ = smodel(t_dense)               # 3×B, (Ŝ, Ĩ, Ř)
G̃ = gmodel(t_dense)               # 2×B, (g_S, g_R) for S and R eqs

# 2. Extract features and targets, promote to Float64 for SR
Ŝ = Float64.(Ỹ[1, :])
Ĩ = Float64.(Ỹ[2, :])
Ř = Float64.(Ỹ[3, :])
t = Float64.(t_vec)

g_S = Float64.(G̃[1, :])
g_R = Float64.(G̃[2, :])

# 3. Feature matrix for SymbolicRegression.jl

X = permutedims(hcat(Ŝ, Ĩ, Ř))  # (3 × B)
#+end_src

#+RESULTS:


#+begin_src julia-vterm

opts_S = SymbolicRegression.Options(
    binary_operators = [+, -, *],
    unary_operators  = [],
    npopulations     = 30,
    maxsize          = 20,
)

hall_of_fame_R = SymbolicRegression.EquationSearch(
    X, g_S;
    niterations = 200,
    options     = opts_S,
    # parallelism = :multithreading,
    progress    = false,
    # verbosity   = 0,
    variable_names   = ["S_norm", "I_norm", "R_norm"],
)

dominating_R = SymbolicRegression.calculate_pareto_frontier(hall_of_fame_R)
trees_R      = [m.tree for m in dominating_R]
#+end_src

#+RESULTS:

#+begin_src julia-vterm

opts_R = SymbolicRegression.Options(
    binary_operators = [+, -, *],
    unary_operators  = [],
    npopulations     = 30,
    maxsize          = 20,
)

hall_of_fame_R = SymbolicRegression.EquationSearch(
    X, g_R;
    niterations = 200,
    options     = opts_R,
    # parallelism = :multithreading,
    progress    = false,
    # verbosity   = 0,
    variable_names   = ["S", "I", "R"],
)

dominating_R = SymbolicRegression.calculate_pareto_frontier(hall_of_fame_R)
trees_R      = [m.tree for m in dominating_R]
#+end_src

#+RESULTS:
: Executing... 44de58ef
